import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TxtService {

  // max char 192

  text: Array<any> = [
    { id: 1, t: 'Drink if you ever had a relationship' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 3, t: 'Drink if you ever sent a picture to somebody not everyone should see' },
    { id: 4, t: 'Drink if you ever broke up with someone via text' },
    { id: 5, t: 'Drink if you ever kissed a stranger' },
    { id: 6, t: 'Drink if you ever tried to write a song' },
    { id: 7, t: 'Drink if you ever dated a coworker' },
    { id: 8, t: "Drink if you've ever been kicked between your legs" },
    { id: 9, t: 'Drink if you ever done something illegal' },
    { id: 10, t: 'Drink if you ever lied to your partner' },
    { id: 11, t: 'All who has brown eyes take 2 sips' },
    { id: 12, t: 'The last one to stand up must gets 2 sips' },
    { id: 13, t: 'Take a sip for each apple product you own ' },
    { id: 14, t: 'If you ever puked because of alcohol, shame on you! Take 3 sips' },
    { id: 15, t: "If you've ever  been on tv, you can give out a sip" },
    { id: 16, t: 'Everybody take a  sip' },
    { id: 17, t: 'All who has white on their shoes must drink 2 sips' },
    { id: 18, t: 'The one with the expensivest shoes,might have the most drip and can give out a sip' },
    { id: 19, t: 'The least amount of people present of the same gender must take 2 sips' },
    { id: 20, t: 'All who do not know how many stripes pikachu has on his back, is a disgrace. Finish your drink!' },
    { id: 21, t: 'The youngest can ask a question to the person of choice. That person must answer or take 3 sips' },
    { id: 22, t: "Drink the amount of times you went to Mcdonald's this month" },
    { id: 23, t: "Everyone on turn cite pokemons beginning with the letter A. The first who can't come up with one takes 3 sips" },
    { id: 24, t: 'Drink if you ever slept with somebody without remembering' },
    { id: 25, t: "Drink if you ever took someone's virginity" },
    { id: 26, t: "Drink if you've ever had sex in a car" },
    { id: 27, t: 'Drink if you ever had sex with multiple  people in one day' },
    { id: 28, t: 'Drink your bodycount' },
    { id: 29, t: "Drink if you've ever been to a stripclub" },
    { id: 30, t: "Drink if you've ever been skinny dipping" },
    /*
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
    { id: 2, t: 'Drink for each time you went to ikea this month' },
*/
  ]
}
