import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TxtService {

  // max char 192

  text: Array<any> = [
    { id: 0, t: "Drink if you've ever been in a relationship with someone 5 years older" },
    { id: 1, t: "Drink for each time you went to ikea this month" },
    { id: 2, t: "Drink if you've ever sent a photo to someone not everyone should see" },
    { id: 3, t: "Choose a commonly used word. The person who uses that word must take a sip. Valid for 30 min" },
    { id: 4, t: "Drink if you've ever broken up with someone via text" },
    { id: 5, t: "Drink if you've ever kissed a stranger" },
    { id: 6, t: "Drink if you've ever tried to write a song" },
    { id: 7, t: "Drink if you've ever dated a coworker" },
    { id: 8, t: "Drink if you've ever been kicked between your legs" },
    { id: 9, t: "Drink if you've ever done something illegal" },
    { id: 10, t: "Drink if you've ever lied to your partner" },
    { id: 11, t: "All who has brown eyes take 2 sips" },
    { id: 12, t: "The last one to stand up must gets 2 sips" },
    { id: 13, t: "Take a sip for each apple product you own " },
    { id: 14, t: "If you've ever puked because of alcohol, shame on you! Take 3 sips" },
    { id: 15, t: "If you've ever  been on tv, you can give out a sip" },
    { id: 16, t: "Everybody takes a sip" },
    { id: 17, t: "All who has white on their shoes must drink 2 sips" },
    { id: 18, t: "The one with the expensivest shoes,might have the most drip and can give out a sip" },
    { id: 19, t: "The least amount of people present of the same gender must take 2 sips" },
    { id: 20, t: "All who do not know how many stripes pikachu has on his back, is a disgrace. Finish your drink!" },
    { id: 21, t: "The youngest can ask a question to the person of choice. That person must answer or take 3 sips" },
    { id: 22, t: "Drink the amount of times you went to Mcdonald's this month" },
    { id: 23, t: "Everyone on turn names pokemons beginning with the letter A. The first who can't come up with one takes 3 sips" },
    { id: 24, t: "Drink if you've ever slept with somebody without remembering" },
    { id: 25, t: "Drink if you've ever took someone's virginity" },
    { id: 26, t: "Drink if you've ever had sex in a car" },
    { id: 27, t: "Drink if you've ever had sex with multiple people in one week" },
    { id: 28, t: "Drink your bodycount" },
    { id: 29, t: "Drink if you've ever been to a stripclub" },
    { id: 30, t: "Drink if you've ever been skinny dipping" },
    { id: 31, t: "Speak loud as if everyone is deaf for one entirely round. Take 2 sip each time you forget" },
    { id: 32, t: "Pretend you are cumming, the person who acts best can give 5 sips" },
    { id: 33, t: "Start a facebook live session, the one with the fewest viewers take 2 sips" },
    { id: 34, t: "Call someone of your choice if they answer take 2 sips if not give out 2 sips" },
    { id: 35, t: "Ask your neighbors for condoms or take 5 sips" },
    { id: 36, t: "Whisper for a whole round. Take 2 sips every time you forget" },
    { id: 37, t: "Everyone whispers for 3 whole rounds. Take 2 sips every time you forget" },
    { id: 38, t: "If you've ever had sex outside, you a brave one. Take a sip." },
    { id: 39, t: "If you've ever thought of someone here in a sexual way take a long sip" },
    { id: 40, t: "Every time someone uses a swear word, that word is written on that person" },
    { id: 41, t: "If you've ever seen '2 girls 1 cup' , you can rest easy you've already suffered enough. Give out 3 sips" },
    { id: 42, t: "The one with the fullest drink must drink half of it n one go" },
    { id: 43, t: "The one with the emptiest drink can give the whole drink to the person of choice" },
    { id: 44, t: "Kiss your left neighbour or finish your drink" },
    { id: 45, t: "Choose a partner. On 3 shoot the first number that comes up in your head. The one with the lowest number drinks the difference" },
    { id: 46, t: "If you've ever ghosted someone, you're the worst. Drink 2 sips" },
    { id: 47, t: "If you've ever slept with someone that your parents wouldn't approve of, you're a lil baddie. take a sip" },
    { id: 48, t: "Everyone shoots a pickup line. The best one can give out a sip" },
    { id: 49, t: "The last to have a sexual experience takes off a piece of clothing" },
    { id: 50, t: "Everyone drinks with his left hand, take a sip if you forget. Valid for 30 min" },
    { id: 51, t: "Drink if you've ever dated someone you knew you didn't deserve" },
    { id: 52, t: "Post 'pls like #Amigos' as a Facebook status. Wait 30 min. Drink the number of likes you get." },
    /*{ id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
  { id: 2, t: "Drink for each time you went to ikea this month" },
*/
  ]
}
